// STEP-2 DESIGN THE STATE NEEDED FOR THE APP
export const FETCH_JOKE_START="FETCH_JOKE_START";
export const FETCH_JOKE_SUCCESS="FETCH_JOKE_SUCCESS";
export const FETCH_JOKE_FAILURE="FETCH_JOKE_FAILURE";