// STEP-2 DESIGN THE TYPES OF ACTION THE STATE MIGHT SUFFER

//fetching pokemon
export const GET_POKEMON_START = 'GET_POKEMON_START'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
//spinner
export const SPINNER_START = 'SPINNER_START'
export const SPINNER_STOP = 'SPINNER_STOP'
